### ISSUE TITLE
how to enable this pluguin?

### ISSUE THREAD

**Issue by jiqiujia** [uarun/vim-protobuf#3]

**Comment by uarun** [comment]
The README of this project has an `Installation` section that provides instructions for enabling it under `Pathogen` and `Vundle`

**Comment by jiqiujia** [comment]
yeah, I already have it done. But it makes no difference to my prototxt

**Comment by uarun** [comment]
Does your proto file have the `.proto` extension ? For example: `MyDef.proto`

**Comment by jiqiujia** [comment]
no....what about `.prototxt` ?

**Comment by uarun** [comment]
See:
https://github.com/uarun/vim-protobuf/blob/master/ftdetect/proto.vim

**Comment by jiqiujia** [comment]
sorry, I'm not familiar with the coding of vim pluguin.
I try to replace `proto` with `prototxt`, but it doesn't work.

**Comment by jiqiujia** [comment]
actually, the format of `prototxt` is very simple.Somewhat like this:

```
layers {
  bottom: "conv1"
  top: "conv1"
  name: "relu1"
  type: RELU
}
layers {
  bottom: "conv1"
  top: "pool1"
  name: "pool1"
  type: POOLING
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
```

I just want to have smart indent when begin a new line and some kinds of simple highlight.
Could you recommend me some simple tutorials to start up on this work?

**Comment by uarun** [comment]
The format you've is not what this plugin is for. This plugin is for syntax highlighting Google Protocol Buffers message definitions. From the text you pasted it looks like you are almost working with pretty printed protocol buffer messages (not sure why you would want to edit them by hand).

In any case, without making any changes to this plugin. You should be able to open your file and do

```
:se syntax=proto
```

and get what you want.
